### ISSUE TITLE
Assertion '_M_stddev > _RealType(0)' failed

### ISSUE THREAD

**Issue by AchmadFathoni** [Gepetto/ouster-gazebo-simulation#2]
https://github.com/Gepetto/ouster-gazebo-simulation/blob/fc154c1e6f96edd558a80535a492a66b1b285da9/ouster_os1_64/urdf/os1_64.urdf.xacro#L84-L88

That snippet triggers this error in my ROS Noetic and Gazebo 11.5.1
```
/usr/include/c++/11.1.0/bits/random.h:1992: std::normal_distribution<_RealType>::param_type::param_type(_RealType, _RealType) [with _RealType = double]: Assertion '_M_stddev > _RealType(0)' failed.

```

I guess this problem only happen in my bleeding edge Arch Linux. I hope this issue will be useful as future reference.

**Comment by nim65s** [comment]
Your GCC 11.1.0 defaults to C++17. This package is not yet compatible with C++17.
This is already in my todolist, but meanwhile, can you try with `-DCMAKE_CXX_STANDARD=14` ?

**Comment by AchmadFathoni** [comment]
`-DCMAKE_CXX_STANDARD=14` makes no different unfortunately. I have tried to recompile both this package and Gazebo itself.

**Comment by TLasguignes** [comment]
@nim65s if this issue still needs to be solved, can we have a noetic base to reproduce the error?

**Comment by nim65s** [comment]
Actually, now that I'm testing this again on Arch, it is the other way around.

`ouster_gazebo_plugins` doesn't build with GCC 11.1.0 by default, but with `-DCMAKE_CXX_STANDARD=14` (or 17), it works. With clang (12.0.1), the default works.

It looks like many ros-noetic packages on AUR have a `-DCMAKE_CXX_STANDARD=17`, so maybe catkin or another ROS dependency is stupidly forcing C++11 somewhere, and we have to manually override that… I don't know.

**Comment by TLasguignes** [comment]
As it was stated on the first message, the errors seems to come from 
```xml
<noise>
  <type>gaussian</type>
  <mean>0.0</mean>
  <stddev>0.0</stddev>
</noise>
```

I guess we can simply remove this part. Indeed, the generated noise is handled in the plug-in, starting [l.331](https://github.com/Gepetto/ouster-gazebo-simulation/blob/master/ouster_gazebo_plugins/src/GazeboRosOusterLaser.cpp#L311). This bloc should have set the noise as null to ensures that it is only the product of the plug-in.
I also guess that a better way to wrote this block should be with `<type>none</type>`.

These guesses should remove the errors but will certainly not explain why this error's appearance is dependant of the C++ standard.

**Comment by Leeable** [comment]
the issue is that, According to the C++ documentation, creating a std::normal_distribution with [stddev <= 0 is undefined behavior](https://en.cppreference.com/w/cpp/numeric/random/normal_distribution/normal_distribution). So` <stddev>0.0</stddev>` is not accepted, we can set it like `<stddev>0.00000001</stddev>`, and it works fine .
